
###############################################################################
#                               Linter Settings                               #
###############################################################################
linters-settings:
  dupl:
    threshold: 100
  errcheck:
    check-type-assertions: true
    check-blank: true
  exhaustive:
    check-generated: false
    default-signifies-exhaustive: true
  funlen:
    lines: 100
    statements: 50
  gci:
    sections:
     - prefix(github.com/rigup/ephemeral-iam)
  goconst:
    min-len: 2
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - appendAssign
      - dupImport # https://github.com/go-critic/go-critic/issues/845
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
  godot:
    scope: all
    exclude: []
    capital: false
  godox:
    keywords: # default keywords are TODO, BUG, and FIXME, these can be overwritten by this setting
      - TODO
      - BUG
      - FIXME
      - NOTE
      - OPTIMIZE # marks code that should be optimized before merging
      - HACK # marks hack-arounds that should be removed before merging
  goimports:
    local-prefixes: github.com/rigup/ephemeral-iam
  lll:
    line-length: 120
  misspell:
    locale: US
  nolintlint:
    allow-unused: false # report any unused nolint directives
    require-explanation: false # don't require an explanation for nolint directives
    require-specific: false # don't require nolint directives to be specific about which linter is being skipped

###############################################################################
#                               Enabled Linters                               #
###############################################################################
linters:
  disable-all: true
  enable:
    - bodyclose
    # - depguard
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - funlen
    - goconst
    - gochecknoinits
    - gocritic
    - gocyclo
    - godot
    # - godox
    - gofmt
    - goimports
    #- gomnd failing with magic numbers
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
    # don't enable:
    # - asciicheck
    # - scopelint
    # - gochecknoglobals
    # - gocognit
    # - goerr113
    # - interfacer
    # - maligned
    # - nestif
    # - prealloc
    # - testpackage
    # - revive check why this is disable since its replacing golint
    # - wsl

###############################################################################
#                                 Run Options                                 #
###############################################################################
run:
  concurrency: 8
  # allow-parallel-runners: true
  tests: false
  timeout: 3m

###############################################################################
#                                Output Options                               #
###############################################################################
output:
  # colored-line-number|line-number|json|tab|checkstyle|code-climate|junit-xml|github-actions
  formats:
    - format: tab
      path: stdout
  sort-results: true

###############################################################################
#                             Issue Configuration                             #
###############################################################################
issues:
  # List of regexps of issue texts to exclude
  exclude: []

  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - errcheck
        - dupl
        - gosec
    - path: cmd
      linters:
        - dupl

    # Exclude some staticcheck messages
    # - linters:
    #     - staticcheck
    #   text: "SA9003:"

    # Exclude lll issues for long lines with go:generate
    - linters:
        - lll
      source: "^//go:generate "

  # Maximum issues count per one linter. Set to 0 to disable. Default is 50.
  max-issues-per-linter: 0

  # Maximum count of issues with the same text. Set to 0 to disable. Default is 3.
  max-same-issues: 0

  # Show only new issues: if there are unstaged changes or untracked files,
  # only those changes are analyzed, else only changes in HEAD~ are analyzed.
  new: false

  # Fix found issues (if it's supported by the linter)
  fix: true

###############################################################################
#                             Issue Severity                                  #
###############################################################################
severity:
  default-severity: error
  # If set to true severity-rules regular expressions become case sensitive.
  case-sensitive: false

  rules:
    - linters:
      - dupl
      - godox
      severity: info
