name: Test
on: [pull_request]
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.3
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@main
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - run: |-
          cp $GOOGLE_APPLICATION_CREDENTIALS ~/.config/gcloud/application_default_credentials.json
      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        id: install
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Test
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ""
        run: go test ./cmd/...
