name: Test
on: [pull_request]
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Test
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ""
        run: go test -race -v ./cmd/...
